# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

- name: Verify required variables for selected role
  ansible.builtin.include_tasks: variables_assertion.yml

- name: "Edit cluster IP address for vManage {{ (vmanage_instances | first).hostname }}"
  cisco.catalystwan.cluster_management:
    wait_until_configured_seconds: 300
    vmanage_id: "0"
    system_ip: "{{ (vmanage_instances | first).system_ip }}"
    cluster_ip: "{{ (vmanage_instances | first).cluster_private_ip }}"
    username: "{{ (vmanage_instances | first).admin_username }}"
    password: "{{ (vmanage_instances | first).admin_password }}"
    persona: "{{ (vmanage_instances | first).persona }}"
    services: "{{ (vmanage_instances | first).cluster_services | default(default_services) }}"
    manager_authentication:
      url: "{{ (vmanage_instances | first).mgmt_public_ip }}"
      username: "{{ (vmanage_instances | first).admin_username }}"
      password: "{{ (vmanage_instances | first).admin_password }}"
  retries: 12
  delay: 10

- name: Add remaining instances to cluster
  cisco.catalystwan.cluster_management:
    wait_until_configured_seconds: 1800
    system_ip: "{{ vmanage.system_ip }}"
    cluster_ip: "{{ vmanage.cluster_private_ip }}"
    username: "{{ vmanage.admin_username }}"
    password: "{{ vmanage.admin_password }}"
    gen_csr: false
    persona: "{{ vmanage.persona }}"
    services: "{{ vmanage.cluster_services | default(default_services) }}"
    manager_authentication:
      url: "{{ (vmanage_instances | first).mgmt_public_ip }}"
      username: "{{ (vmanage_instances | first).admin_username }}"
      password: "{{ (vmanage_instances | first).admin_password }}"
  loop: "{{ vmanage_instances[1:] }}"
  loop_control:
    loop_var: vmanage
  when: vmanage.cluster_private_ip is defined
  retries: 36
  delay: 10
