- name: Dependency Task Without Handlers/Register Demo
  hosts: servera*
  gather_facts: false
  tasks:
    # List of tasks
    # - name: Install Web Package
    #   ansible.builtin.dnf:
    #     name: httpd
    #     state: present
    #   become: true
      

    - name: Deploy Web app
      ansible.builtin.copy:
        content: "EU LISA Index Page"
        dest: /var/www/html/index.html
        mode: 0644
      become: true
      register: app_captured


    - name: Print Output var
      ansible.builtin.debug:
        var: app_captured.checksum

    - name: Print Output msg
      ansible.builtin.debug:
        msg: "Checksum = {{ app_captured.checksum }}"
        # var: app_captured.checksum
