- name: Configure Web Server
  hosts: servera*
  become_user: root
  gather_facts: false
  remote_user: devops
  become: true
  tasks:
    # List of tasks
    - name: Install Web Package
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Deploy Web app
      ansible.builtin.copy:
        content: "EU LISA Index Page"
        dest: /var/www/html/index.html
        mode: 0644


    - name: Start Web Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Open Firewall Port
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

- name: Test Web Server
  hosts: workstation.lab.example.com
  gather_facts: false
  remote_user: student
  become: false
  tasks:
    - name: Check Web Page
      ansible.builtin.uri:
        url: http://servera.lab.example.com
        return_content: true
      register: captured

    - name: Print the Output
      ansible.builtin.debug:
        msg: "{{ captured.content }}"
