- name: Template App of Web Server
  hosts: all
  # gather_facts: false
  become: true
  tasks:
    - name: Set Fact for Group Names
      ansible.builtin.set_fact:
        mygroups: "{{ group_names }}"

    - name: Blokc to Collect Info
      block:
        - name: Install Web Package
          ansible.builtin.dnf:
            name: httpd
            state: present

        - name: Deploy Web app
          ansible.builtin.template:
            src: j2/complex.j2
            #src: j2/simple.j2
            dest: /var/www/html/index.html
            mode: 0644


        - name: Start Web Service
          ansible.builtin.service:
            name: httpd
            state: started
            enabled: true

        - name: Open Firewall Port
          ansible.posix.firewalld:
            service: http
            permanent: true
            state: enabled
            immediate: true
      when: inventory_hostname in groups["control"]
