- name: Variable Demo
  hosts:
    - dev
    - test
    - prod
  gather_facts: false
  vars:
    print_floor_level: "Level 12 Play Vars"

  # Development Level ONLY
  vars_prompt:
    - name: print_floor_level
      prompt: "Enter Level"
      private: false

  vars_files:
    - vars/outside_vars.yml

  roles:
    - role: print

  tasks:
    - name: Outside Block Task 1
      ansible.builtin.debug:
        msg: "{{ print_floor_level }} {{ users.bjones.first_name }} {{ users['acook']['home_dir'] }} {{ myvar }}"

    - name: Block of Insiders
      block:
        - name: Inside Block Task 2
          ansible.builtin.debug:
            msg: "{{ print_floor_level }}"
          vars:
            print_floor_level: "Level 17 Task Vars"

        - name: Inside Block Task 3
          ansible.builtin.debug:
            msg: "{{ print_floor_level }}"
      when: youyou is not defined
      vars:
        print_floor_level: "Level 16 Block Vars"


    - name: Outside Block Task 4
      ansible.builtin.debug:
        msg: "{{ print_floor_level }}"
