---
# tasks file for roles/security_server

- name: Install Security Package
  ansible.builtin.dnf:
    name: "{{ security_server_package }}"
    state: present
  notify:
    - Security packages installed
    - Restart Security Service

- name: Open Firewall Port
  ansible.posix.firewalld:
    service: "{{ security_server_port }}"
    permanent: true
    state: enabled
    immediate: true
  notify:
    - Restart Security Service
    - port opened
