---
# defaults file for web_server

web_server_package: httpd
web_server_service: httpd
web_server_state: present
web_server_content: "Level 2 Defaults -- EU LISA Index Page"
web_server_dest: /var/www/html/index.html
