name: Static Code Analyzer

on:
  pull_request:

  push:
    branches:
      - master

permissions: read-all

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    defaults:
      run:
        shell: sh

    steps:
      - name: Check out the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: '3.10'

      - uses: isort/isort-action@master
        with:
          requirementsFiles: "requirements.txt"

      - name: Install pycln
        run: pip install pycln==2.4.0

      - name: Run pycln
        run: pycln --all .

      - name: Run check-yaml, end-of-file-fixer, trailing-whitespace
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

      - name: Run ansible-lint
        uses: ansible/ansible-lint@95382d398ea1744bf6bfa47b030f14c38b3f6957 # v24.7.0

      - name: Install detect-secrets
        run: pip install detect-secrets==1.4.0

      - name: Run detect-secrets
        run: detect-secrets scan
