download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cisco-catalystwan-0.3.2.tar.gz
format_version: 1.0.0
name: catalystwan
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.3.2
version_url: /api/v3/plugin/ansible/content/published/collections/index/cisco/catalystwan/versions/0.3.2/
