# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

- name: Verify required variables for selected role
  ansible.builtin.include_tasks: variables_assertion.yml

- name: "Health check: control connections - verifies if all have state up"
  cisco.catalystwan.health_checks:
    check_type: control_connections
    manager_authentication:
      url: "{{ (vmanage_instances | first).mgmt_public_ip }}"
      username: "{{ (vmanage_instances | first).admin_username }}"
      password: "{{ (vmanage_instances | first).admin_password }}"
  retries: 20

- name: "Health check: orchestrator connections - verifies if all have state up"
  cisco.catalystwan.health_checks:
    check_type: orchestrator_connections
    manager_authentication:
      url: "{{ (vmanage_instances | first).mgmt_public_ip }}"
      username: "{{ (vmanage_instances | first).admin_username }}"
      password: "{{ (vmanage_instances | first).admin_password }}"

# NOTE: system status checks are commented, because it can take up to 1hour for device after onboarding to report them
# - name: |
#     "Health check: system status with health metrics - vmanage:
#     - cpu_state == normal
#     - mem_state == normal
#     - mem_usaage <= 90
#     - device_status == normal
#     - device_reachablitiy = reachable
#   cisco.catalystwan.health_checks:
#     check_type: device_system_status
#     filters:
#       personality: "vmanage"
#     manager_authentication:
#       url: "{{ (vmanage_instances | first).mgmt_public_ip }}"
#       username: "{{ (vmanage_instances | first).admin_username }}"
#       password: "{{ (vmanage_instances | first).admin_password }}"

# - name: |
#     "Health check: system status with health metrics - vsmart:
#     - cpu_state == normal
#     - mem_state == normal
#     - mem_usaage <= 90
#     - device_status == normal
#     - device_reachablitiy = reachable
#   cisco.catalystwan.health_checks:
#     check_type: device_system_status
#     filters:
#       personality: "vsmart"
#     manager_authentication:
#       url: "{{ (vmanage_instances | first).mgmt_public_ip }}"
#       username: "{{ (vmanage_instances | first).admin_username }}"
#       password: "{{ (vmanage_instances | first).admin_password }}"

# - name: |
#     "Health check: system status with health metrics - vbond:
#     - cpu_state == normal
#     - mem_state == normal
#     - mem_usaage <= 90
#     - device_status == normal
#     - device_reachablitiy = reachable
#   cisco.catalystwan.health_checks:
#     check_type: device_system_status
#     filters:
#       personality: "vbond"
#     manager_authentication:
#       url: "{{ (vmanage_instances | first).mgmt_public_ip }}"
#       username: "{{ (vmanage_instances | first).admin_username }}"
#       password: "{{ (vmanage_instances | first).admin_password }}"

- name: "Health check: BFD sessions - verifies if all have state up"
  cisco.catalystwan.health_checks:
    check_type: bfd
    manager_authentication:
      url: "{{ (vmanage_instances | first).mgmt_public_ip }}"
      username: "{{ (vmanage_instances | first).admin_username }}"
      password: "{{ (vmanage_instances | first).admin_password }}"

- name: "Health check: OMP sessions - verifies if all have state up"
  cisco.catalystwan.health_checks:
    check_type: omp
    manager_authentication:
      url: "{{ (vmanage_instances | first).mgmt_public_ip }}"
      username: "{{ (vmanage_instances | first).admin_username }}"
      password: "{{ (vmanage_instances | first).admin_password }}"
